### ISSUE TITLE
Zerschießt Contao 4.13.36 

### ISSUE THREAD

**Issue by dtptiger** [RhymeDigital/contao_backend_rhyme#44]
Contao 4.13.36 (API-Version 2) gefunden. Datenbank-Problem gefunden.

An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'soulxxx_1.tl_vee_element_set_group' doesn't exist

Dann soll ich ne neue Datenbank einrichten.

Im Manager kann ich diese Extension nicht löschen.

**Comment by rhymeadam** [comment]
@dtptiger Fixed in #45

**Comment by dtptiger** [comment]
Danke für das schnellste Fixen aller Zeiten👍, euer theme ist eleganter, nur noch nicht so ganz wirklich ausgereift, u.A. sind die icons etwas klobig geraten – oder ist das für handhelds so gewollt, denn da sind Icons etwas sehr fummelig,
